name = "usad-competition-management-backend"
main = "src/index.ts"
compatibility_date = "2025-09-28"
type = "module"

[[d1_databases]]
binding = "DB"
database_name = "usad-main-db"
database_id = "" #TODO
migrations_dir = "../../packages/database/prisma/migration/d1"