export const schoolSelectFieldsSchema = {
  id: true,
  externalSchoolId: true,
  name: true,
  isVirtual: true,
  streetAddress: true,
  city: true,
  state: true,
  zipCode: true,
  phone: true,
  principalName: true,
  principalEmail: true,
  primaryCoachId: true,
  emailDomain: true,
  division: true,
  objectiveScore: true,
  subjectiveScore: true,
};
