export const studentSelectFieldsSchema = {
  id: true,
  externalStudentId: true,
  division: true,
  gpa: true,
  firstName: true,
  lastName: true,
  teamId: true,
  schoolId: true,
  signature: true,
  streetAddress: true,
  city: true,
  state: true,
  zipCode: true,
  guardianFirstName: true,
  guardianLastName: true,
  guardianPhone: true,
  guardianEmail: true,
};