export const competitionsFieldsSchema = {
  id: true,
  name: true,
  startsAt: true,
  endsAt: true,
  events: true,
  mutationIndex: true,
  competitionAvailableStates: true,
  round: true,
  nonRelativeEvents: true,
  streetAddress: true,
  city: true,
  state: true,
  zipCode: true,
};
